### ISSUE TITLE
Add name to the notify icon

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/tray-windows#14]
The notify icon on the notify are has no name. It would be recommended to set a name for it.

Inspecting the rest of the icons on the notify area all have name so it seems the standard. Also this would be useful for automated ui testing (using the name as selector for the icon).

**Comment by gbraad** [comment]
Looking into this.

I did add accessible names to the fields and other elements

**Comment by anjannath** [comment]
Done via #96
