### ISSUE TITLE
Error message on cluster start

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/tray-windows#19]
### CRC version 

1.22.0

### Description

Starting the cluster from the tray, the cluster is started properly but an error is shown:

![crc_1 22 0_tray_error](https://user-images.githubusercontent.com/1957899/107210304-3ebe3b80-6a04-11eb-90fe-b513dfcc0e5d.png)

Here is the [full log](https://gist.github.com/adrianriobo/ac238659d2c8b3b56f167620cab91c7e#file-error-log)

**Comment by cfergeau** [comment]
Looks like it fails to parse the json answer it got for the `start` command, some issue with the `ClusterConfig.ClusterCACert` field. I don't know if the tray prints the json it received before trying to parse it. @anjannath ?

**Comment by anjannath** [comment]
> 
> 
> Looks like it fails to parse the json answer it got for the `start` command, some issue with the `ClusterConfig.ClusterCACert` field. I don't know if the tray prints the json it received before trying to parse it. @anjannath ?

No it doesn't print the json, since logs can all be viewed when running from the Visual Studio IDE

Found the bug though, it was actually two things the size of the buffer was too small so we were receiving partial JSON from the daemon, and the `ClusterConfig` structure changed
