### ISSUE TITLE
Detailed status window information not updated

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/tray-windows#20]
### CRC version

1.22.0

### Description

When starting the cluster from the tray the status detailed window information is never updated. It always shows empty values:

![crc_1 22 0_tray_detailed_status_not_updated](https://user-images.githubusercontent.com/1957899/107210876-08cd8700-6a05-11eb-97d4-918f02fdda59.png)

**Comment by anjannath** [comment]
This looks like a side effect of uncaught exception, when the error mentioned in #19 happens, the execution doesn't continue and hence when we click on the `Status` the status is not updated. however if the tray is restarted after the error in #19 occurs the status window gets populated with all the information.
