### ISSUE TITLE
Downgrade to .NET 4.5 so can build with Fedora+Mono 6.8.0

### ISSUE THREAD

**Issue by gbraad** [code-ready/tray-windows#22]
When the TargetFramework is changed from:

```diff
     <AssemblyName>tray-windows</AssemblyName>
-    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
+    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>^M
     <FileAlignment>512</FileAlignment>
```

in `tray-windows.csproj` it is possible to build the project on Mono:

For example:
```dockerfile
FROM fedora:latest

RUN dnf install -y mono-devel nuget git-core && \
    nuget update -self && \
    git clone https://github.com/code-ready/tray-windows.git

RUN sed -i 's/4.7.2/4.5/g' tray-windows.csproj

RUN cd tray-windows && \
    nuget restore && \
    xbuild tray-windows.sln

```
would result in an executable that might run on Windows. Haven't been able to fully test this yet...

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/108316073-53b28000-71f7-11eb-8e49-76539c184a85.png)
works

**Comment by gbraad** [comment]
@anjannath I accidently committed this change to master. Can you verify this still works on Windows with the regular toolchain?

was supposed to be a recreative effort...
still on PTO... ;-)

... accidently made it into work!

**Comment by anjannath** [comment]
@gbraad It works with the existing build process from Visual Studio.
