### ISSUE TITLE
Add buildscript for Linux

### ISSUE THREAD

**Issue by gbraad** [code-ready/tray-windows#23]
This container works to build the project:
```Dockerfile
FROM fedora:latest

RUN dnf install -y mono-devel nuget git-core && \
    nuget update -self && \
    git clone https://github.com/code-ready/tray-windows.git

RUN cd tray-windows && \
    nuget restore && \
    xbuild tray-windows.sln
```

need to add a Makefile to perform the actual build steps.

Related to #22

**Comment by cfergeau** [comment]
Rather than `git clone https://github.com/code-ready/tray-windows.git`, I'd favour `COPY . .`, you usually want to test build what is in your local tree (which will match `origin/master` in CI, but can be something with local changes).

**Comment by gbraad** [comment]
This was JUST the test script to show this works. Of ocurse a copy will be used
