### ISSUE TITLE
Create config window

### ISSUE THREAD

**Issue by anjannath** [code-ready/tray-windows#5]
Create a similar config window UI like the macOS tray

**Comment by anjannath** [comment]
![settings-advanced](https://user-images.githubusercontent.com/8885742/100722473-a6de1900-33e6-11eb-9514-9b4f34ef15b5.PNG)
![settings-basic](https://user-images.githubusercontent.com/8885742/100722477-a8a7dc80-33e6-11eb-8753-c4fd167a1480.PNG)

**Comment by gbraad** [comment]
True false should likely be represented by checkboxes?

**Comment by anjannath** [comment]
@gbraad The reason i went with the drop down selectors is because there are 3 options in total, that is because the `skip-check-*` and `warn-check-*` is combined into one single config option for the tray UI.

 e.g `skip-check-bundle-cache` and `warn-check-bundle-cache` is called as `Check bundle cached` now the possible options for this config are `skip, warn or unset` and that is presented as a drop down selection.
![Screenshot (2)](https://user-images.githubusercontent.com/8885742/102853572-97cb1380-4446-11eb-8d08-dc6f0c6b95e2.png)

**Comment by gbraad** [comment]
Do we need warn for the user?

**Comment by gbraad** [comment]
Perhaps only a skip preflight checks would be enough

**Comment by anjannath** [comment]
> 
> 
> Do we need warn for the user?
> They mostly exist for debug and solving a breaking change.
> 
> Perhaps only a skip preflight checks would be enough

Yes skip should be enough, we can remove the warn option, and replace the dropdown with radio button, have to do the same for macOS.

**Comment by anjannath** [comment]
Changed them to be a checkbox, check #16

**Comment by gbraad** [comment]
Please include if possible the single toggle: https://github.com/code-ready/crc/issues/1796 Checking this would have to disable the rest of the checkboxes to be disabed?

**Comment by anjannath** [comment]
Sure, will update the PR on this repo, required PR on crc  https://github.com/code-ready/crc/pull/1804

**Comment by anjannath** [comment]
Closing as the initial config window is done in https://github.com/code-ready/tray-windows/pull/16
