### ISSUE TITLE
Fix size of settings window

### ISSUE THREAD

**Issue by gbraad** [code-ready/tray-windows#56]
Change 0dbea91 now makes the window jump around. Actually this feels bad ... as due to buttons moving to a new place, it feels like this might break the mental model.

**Comment by anjannath** [comment]
The change was intended to only resize the window (by adjusting the height), it should not jump around, maybe because we want to center the window that makes it change the window position on the screen?

**Comment by anjannath** [comment]
@gbraad Can this be closed, or do you still see this issue?
