### ISSUE TITLE
Tray is blurry: font is not the same as the system

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/tray-windows#74]
<img width="890" alt="blurry" src="https://user-images.githubusercontent.com/172624/120606587-326f4b80-c404-11eb-8203-51f3c9753507.PNG">

**Comment by gbraad** [comment]
ClearType enabled?

**Comment by guillaumerose** [comment]
Same result with and without ClearType.

**Comment by gbraad** [comment]
To which part are you actually referring? the top with Segoe or the log with the fixed width Serif font?
It is a compressed image and scaled and it all looks blurry now... not like on my machine

**Comment by gbraad** [comment]
Please check your DPI settings

**Comment by gbraad** [comment]
* https://www.ghacks.net/2020/01/02/the-perils-of-running-windows-10-on-a-4k-monitor/
  * http://crsouza.com/2015/04/13/how-to-fix-blurry-windows-forms-windows-in-high-dpi-settings/

```
    static class Program
    {
        [STAThread]
        static void Main()
        {
            if (Environment.OSVersion.Version.Major &gt;= 6)
                SetProcessDPIAware();
 
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }
 
        [System.Runtime.InteropServices.DllImport("user32.dll")]
        private static extern bool SetProcessDPIAware();
```

**Comment by anjannath** [comment]
Tried the fix mentioned in http://crsouza.com/2015/04/13/how-to-fix-blurry-windows-forms-windows-in-high-dpi-settings/ and the fonts now do look sharper/crispier, not sure this is recognizable in the screenshots below, but definitely looks better than before..

<img src="https://user-images.githubusercontent.com/8885742/121042605-7a5dec00-c7d1-11eb-956b-98d24ffabb95.png" height="350"/>
<img src="https://user-images.githubusercontent.com/8885742/121042616-7c27af80-c7d1-11eb-9125-d2bd857e3db7.png" height="450"/>

**Comment by anjannath** [comment]
please verify the fix in this PR https://github.com/code-ready/tray-windows/pull/77 :)
