### ISSUE TITLE
Implement dialog with paste option for the pull-secret

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/tray-windows#99]
On tray for macos the behavior for the pull secret request has change. Now it asks for the content.

The windows tray still asks for the pull secret location. 

So the pull secret is handle different on both trays, not only for the asking but for the storage. As the macos uses the keyring but the windows uses the config.

![1 29 1-tray-windows-ps-file](https://user-images.githubusercontent.com/1957899/125070805-bded9380-e0b8-11eb-8d73-f422446bbc86.png)

**Comment by gbraad** [comment]
The inconsistency also comes from the [page](https://cloud.redhat.com/openshift/create/local) where the pull secret is obtained:

![image](https://user-images.githubusercontent.com/1894/125418267-c4bd9a4c-c1c9-4c0a-896a-15d9ecdb3caf.png)

From a documentation POV it would be best to use a single method. /cc: @robin-owen We will allow for the paste option as this leaves no traces behind.

**Comment by gbraad** [comment]
The dialog used on macOS is as follows:
<img width="481" alt="screenshot_2021-07-13_at_10 31 21" src="https://user-images.githubusercontent.com/1894/125421976-467af45c-45f0-4acc-9ac4-28fcf1aa1260.png">
